name: CMake-Server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 50

    steps:
      - uses: actions/checkout@v2

      - name: Update Git Submodules
        run: git submodule update --init --recursive

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev wayland-protocols libwayland-dev libxkbcommon-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: server-${{env.BUILD_TYPE}}

      - name: Configure CMake
        run: cmake rpg -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DRPG_BUILD_SERVER=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j 4

      - uses: actions/upload-artifact@v2
        with:
          name: ${{env.BUILD_TYPE}}
          path: |
            build/**/*.exe
            build/**/rpg*
            build/**/EditorResources
            build/**/EngineResources
            build/**/GameResources
            !build/**/CMakeFiles

      - name: Transfer files to Droplet
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          source: "build"
          target: "/rpgServer"

      - name: SSH into Droplet and setup server auto-start service, and start it
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          passphrase: ${{ secrets.DROPLET_PASSPHRASE }}
          script: |
            cp -f /rpgServer/build/rpg/GameResources/server/rpg-server.service /etc/systemd/system/
            systemctl daemon-reload
            systemctl enable rpg-server
            systemctl stop rpg-server
            systemctl start rpg-server
            systemctl status rpg-server
